# Copyright © 2026 Saleem Abdulrasool <compnerd@compnerd.org>. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

add_subdirectory(CounterABI)
add_subdirectory(CounterSupport)
add_subdirectory(CounterC)
add_subdirectory(CounterCpp)
add_subdirectory(CounterInterfaces)
add_subdirectory(CounterServer)
add_subdirectory(CounterSwiftClient)
add_subdirectory(CounterCxxClient)
